[build]
publish = "public"
command = "git submodule update -f --init --recursive; npm install; ./bin/hugo --gc --minify"
HUGO_ENV = "production"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "git submodule update -f --init --recursive; npm install; ./bin/hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "ngit submodule update -f --init --recursive; pm install; ./bin/hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

